"use client"

import { Button } from "@/components/ui/button"
import { FileDown } from "lucide-react"
import { formatCurrency } from "@/lib/utils"
import { toast } from "sonner"

interface DealExportProps {
    deal: any
}

// Phase 15 Batch D: Export Deal to PDF
export function ExportDealButton({ deal }: DealExportProps) {
    const handleExport = async () => {
        // Generate HTML content for PDF
        const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Deal Summary - ${deal.title}</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
        .header { border-bottom: 2px solid #3b82f6; padding-bottom: 20px; margin-bottom: 30px; }
        .title { font-size: 24px; font-weight: bold; color: #1f2937; margin: 0; }
        .subtitle { color: #6b7280; margin-top: 8px; }
        .section { margin-bottom: 24px; }
        .section-title { font-size: 14px; font-weight: 600; color: #3b82f6; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 12px; }
        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
        .info-item { padding: 12px; background: #f9fafb; border-radius: 8px; }
        .info-label { font-size: 12px; color: #6b7280; margin-bottom: 4px; }
        .info-value { font-size: 16px; font-weight: 600; color: #1f2937; }
        .value-highlight { font-size: 32px; color: #059669; }
        .priority-high { color: #dc2626; }
        .priority-medium { color: #3b82f6; }
        .priority-low { color: #6b7280; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">${deal.title}</h1>
        <p class="subtitle">${deal.company?.name || 'No Company'} • Generated ${new Date().toLocaleDateString()}</p>
    </div>

    <div class="section">
        <div class="section-title">Deal Value</div>
        <div class="value-highlight">${formatCurrency(deal.value)}</div>
    </div>

    <div class="section">
        <div class="section-title">Deal Information</div>
        <div class="info-grid">
            <div class="info-item">
                <div class="info-label">Stage</div>
                <div class="info-value">${deal.stage}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Priority</div>
                <div class="info-value priority-${deal.priority?.toLowerCase()}">${deal.priority || 'Not Set'}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Probability</div>
                <div class="info-value">${deal.probability || 0}%</div>
            </div>
            <div class="info-item">
                <div class="info-label">Source</div>
                <div class="info-value">${deal.source || 'Unknown'}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Expected Close</div>
                <div class="info-value">${deal.expectedClose ? new Date(deal.expectedClose).toLocaleDateString() : 'Not Set'}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Created</div>
                <div class="info-value">${deal.createdAt ? new Date(deal.createdAt).toLocaleDateString() : 'Unknown'}</div>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Contact Information</div>
        <div class="info-grid">
            <div class="info-item">
                <div class="info-label">Contact Name</div>
                <div class="info-value">${deal.contactName || 'Not Set'}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Email</div>
                <div class="info-value">${deal.contactEmail || 'Not Set'}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Phone</div>
                <div class="info-value">${deal.contactPhone || 'Not Set'}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Company</div>
                <div class="info-value">${deal.company?.name || 'Not Set'}</div>
            </div>
        </div>
    </div>

    ${deal.notes ? `
    <div class="section">
        <div class="section-title">Notes</div>
        <p style="color: #374151; line-height: 1.6;">${deal.notes}</p>
    </div>
    ` : ''}

    <div class="footer">
        <p>This document was automatically generated by CRM System.</p>
        <p>Confidential - For internal use only.</p>
    </div>
</body>
</html>
        `

        // Create a new window and print
        const printWindow = window.open('', '_blank')
        if (printWindow) {
            printWindow.document.write(htmlContent)
            printWindow.document.close()

            // Wait for content to load then trigger print
            setTimeout(() => {
                printWindow.print()
            }, 250)

            toast.success("PDF export opened in new window")
        } else {
            toast.error("Please allow popups to export PDF")
        }
    }

    return (
        <Button
            variant="outline"
            size="sm"
            onClick={handleExport}
            className="gap-2"
        >
            <FileDown className="w-4 h-4" />
            Export PDF
        </Button>
    )
}

// Phase 15: Stage Automations Config (data structure for future use)
export const STAGE_AUTOMATIONS = {
    'QUALIFIED': [
        { action: 'create_task', description: 'Schedule discovery call', dueInDays: 2 },
        { action: 'send_email', description: 'Send intro materials' }
    ],
    'PROPOSAL': [
        { action: 'create_task', description: 'Prepare proposal', dueInDays: 3 },
        { action: 'notify', description: 'Alert sales manager' }
    ],
    'NEGOTIATION': [
        { action: 'create_task', description: 'Review contract terms', dueInDays: 1 },
        { action: 'update_probability', value: 70 }
    ],
    'WON': [
        { action: 'send_email', description: 'Send welcome package' },
        { action: 'create_task', description: 'Schedule onboarding call', dueInDays: 1 },
        { action: 'notify', description: 'Celebrate with team! 🎉' }
    ]
}

// Phase 15: Email Preview snippet (would integrate with email API)
export function EmailPreview({ lastEmail }: { lastEmail?: { subject: string, snippet: string, date: Date } }) {
    if (!lastEmail) return null

    return (
        <div className="text-[10px] bg-gray-50 p-2 rounded border border-gray-100 mt-2">
            <div className="flex items-center gap-1 text-gray-500 mb-0.5">
                <span>📧</span>
                <span className="font-medium truncate flex-1">{lastEmail.subject}</span>
            </div>
            <p className="text-gray-400 truncate">{lastEmail.snippet}</p>
        </div>
    )
}
